// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLnbnGxKRZwl0Sw6_cb323xW0C7Cbwwzw',
    appId: '1:8673706602:web:943d6bff5a1cba975f8013',
    messagingSenderId: '8673706602',
    projectId: 'cardiofit-905a8',
    authDomain: 'cardiofit-905a8.firebaseapp.com',
    storageBucket: 'cardiofit-905a8.appspot.com',
    measurementId: 'G-E5BX1TZSG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6kxz5qQRx0XIcGfuXS6eDv4ijaUGbv4U',
    appId: '1:8673706602:android:71b555cddd1b9f415f8013',
    messagingSenderId: '8673706602',
    projectId: 'cardiofit-905a8',
    storageBucket: 'cardiofit-905a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AR5BHY_mYDG7_9oY_I4OCiuASRrQAg0',
    appId: '1:8673706602:ios:112286c1273cb3c95f8013',
    messagingSenderId: '8673706602',
    projectId: 'cardiofit-905a8',
    storageBucket: 'cardiofit-905a8.appspot.com',
    iosClientId: '8673706602-8scdjkv6nn2sln7mgpcbmtrdqpkd9r4t.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.cardiofitdashboard',
  );
}
